[2022-11-01 11:48:20,249] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: example_gcs.list_buckets manual__2022-10-04T22:19:37.973320+00:00 [queued]>
[2022-11-01 11:48:20,262] {taskinstance.py:1037} INFO - Dependencies all met for <TaskInstance: example_gcs.list_buckets manual__2022-10-04T22:19:37.973320+00:00 [queued]>
[2022-11-01 11:48:20,263] {taskinstance.py:1243} INFO - 
--------------------------------------------------------------------------------
[2022-11-01 11:48:20,264] {taskinstance.py:1244} INFO - Starting attempt 2 of 2
[2022-11-01 11:48:20,265] {taskinstance.py:1245} INFO - 
--------------------------------------------------------------------------------
[2022-11-01 11:48:20,281] {taskinstance.py:1264} INFO - Executing <Task(GCSListObjectsOperator): list_buckets> on 2022-10-04 22:19:37.973320+00:00
[2022-11-01 11:48:20,286] {standard_task_runner.py:52} INFO - Started process 708 to run task
[2022-11-01 11:48:20,292] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'example_gcs', 'list_buckets', 'manual__2022-10-04T22:19:37.973320+00:00', '--job-id', '216', '--raw', '--subdir', 'DAGS_FOLDER/dag_teste.py', '--cfg-path', '/tmp/tmpxwxxgtwl', '--error-file', '/tmp/tmpw2v43hug']
[2022-11-01 11:48:20,295] {standard_task_runner.py:77} INFO - Job 216: Subtask list_buckets
[2022-11-01 11:48:20,364] {logging_mixin.py:109} INFO - Running <TaskInstance: example_gcs.list_buckets manual__2022-10-04T22:19:37.973320+00:00 [running]> on host 44262508447e
[2022-11-01 11:48:20,433] {taskinstance.py:1431} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=example_gcs
AIRFLOW_CTX_TASK_ID=list_buckets
AIRFLOW_CTX_EXECUTION_DATE=2022-10-04T22:19:37.973320+00:00
AIRFLOW_CTX_DAG_RUN_ID=manual__2022-10-04T22:19:37.973320+00:00
[2022-11-01 11:48:20,450] {gcs.py:259} INFO - Getting list of the files. Bucket: stack-data-pipeline-combustiveis-brasil-curated; Delimiter: None; Prefix: None
[2022-11-01 11:48:21,188] {taskinstance.py:1718} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py", line 262, in execute
    return hook.list(bucket_name=self.bucket, prefix=self.prefix, delimiter=self.delimiter)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 705, in list
    for blob in blobs:
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 214, in _items_iter
    for page in self._page_iter(increment=False):
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 253, in _page_iter
    page = self._next_page()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 382, in _next_page
    response = self._get_next_page_response()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 442, in _get_next_page_response
    method=self._HTTP_METHOD, path=self.path, query_params=params
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 80, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/stack-data-pipeline-combustiveis-brasil-curated/o?projection=noAcl&prettyPrint=false: sa-airflow-stackdatapipeline@gcpdatapipeline-366601.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket.
[2022-11-01 11:48:21,213] {taskinstance.py:1282} INFO - Marking task as FAILED. dag_id=example_gcs, task_id=list_buckets, execution_date=20221004T221937, start_date=20221101T114820, end_date=20221101T114821
[2022-11-01 11:48:21,248] {standard_task_runner.py:92} ERROR - Failed to execute job 216 for task list_buckets
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/task/task_runner/standard_task_runner.py", line 85, in _start_by_fork
    args.func(args, dag=self.dag)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/cli_parser.py", line 48, in command
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/cli.py", line 92, in wrapper
    return f(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 298, in task_run
    _run_task_by_selected_method(args, dag, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 107, in _run_task_by_selected_method
    _run_raw_task(args, ti)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/cli/commands/task_command.py", line 184, in _run_raw_task
    error_file=args.error_file,
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/utils/session.py", line 70, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1334, in _run_raw_task
    self._execute_task_with_callbacks(context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1460, in _execute_task_with_callbacks
    result = self._execute_task(context, self.task)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/models/taskinstance.py", line 1516, in _execute_task
    result = execute_callable(context=context)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/operators/gcs.py", line 262, in execute
    return hook.list(bucket_name=self.bucket, prefix=self.prefix, delimiter=self.delimiter)
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/providers/google/cloud/hooks/gcs.py", line 705, in list
    for blob in blobs:
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 214, in _items_iter
    for page in self._page_iter(increment=False):
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 253, in _page_iter
    page = self._next_page()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 382, in _next_page
    response = self._get_next_page_response()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/page_iterator.py", line 442, in _get_next_page_response
    method=self._HTTP_METHOD, path=self.path, query_params=params
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/storage/_http.py", line 80, in api_request
    return call()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 291, in retry_wrapped_func
    on_error=on_error,
  File "/home/airflow/.local/lib/python3.7/site-packages/google/api_core/retry.py", line 189, in retry_target
    return target()
  File "/home/airflow/.local/lib/python3.7/site-packages/google/cloud/_http.py", line 484, in api_request
    raise exceptions.from_http_response(response)
google.api_core.exceptions.Forbidden: 403 GET https://storage.googleapis.com/storage/v1/b/stack-data-pipeline-combustiveis-brasil-curated/o?projection=noAcl&prettyPrint=false: sa-airflow-stackdatapipeline@gcpdatapipeline-366601.iam.gserviceaccount.com does not have storage.objects.list access to the Google Cloud Storage bucket.
[2022-11-01 11:48:21,274] {local_task_job.py:154} INFO - Task exited with return code 1
[2022-11-01 11:48:21,328] {local_task_job.py:264} INFO - 0 downstream tasks scheduled from follow-on schedule check
